### PR TITLE
Styling Revamp - Home Page

### PR DESCRIPTION
**Pull request by maxklema**
Re-styled home page, making it scalable and responsive on all devices

### CODE REVIEW

**Comment by grumpy-lions** [comment]
It looks good so far, is there any way to get the CSS to be applied to the other pages?

**Comment by maxklema** [comment]
> It looks good so far, is there any way to get the CSS to be applied to the other pages?

Yes, working on that now!

**Comment by grumpy-lions** [comment]
The images broke.

**Comment by maxklema** [comment]
> The images broke.

I just re-cloned and launched it. Images show up fine on my end?

**Comment by grumpy-lions** [comment]
image
image

**Comment by maxklema** [comment]
> image image

I see. Let me fix this real quick. Sorry.

**Comment by grumpy-lions** [comment]
Can you see if any GGJ photos look good on the site?

**Comment by maxklema** [comment]
> Can you see if any GGJ photos look good on the site?

Let me look in the onedrive.

**Comment by grumpy-lions** [comment]
Images are showing now

**Pull request merged**
