### PR TITLE
Styling changes

### PR DESCRIPTION
**Pull request by grumpy-lions**
Implemented some style changes for the rest of the site.

### CODE REVIEW

**Review by maxklema — COMMENTED** [review]
The styling on each page looks really good!

However, the header and paragraph description tags on each page are too narrow, especially when shrunk down to mobile size. I can fix this.

I also think the panels could benefit from some more styling.

I'm good for the merge, but I may commit to the main branch a few times.

**Comment by grumpy-lions** [comment]
I would hold off, for now. Let me know when you push so that I can check on my end.

**Comment by maxklema** [comment]
@The-Architect01 I added my changes. Let me know what you think. Panels are also scalable now based on screen width.

**Comment by grumpy-lions** [comment]
It looks good on my end. I'll resolve the conflicts and merge.

**Pull request merged**
